# API rarity number to named rarity
RARITIES = {
    0: 'normal',
    1: 'magic',
    2: 'rare',
    3: 'unique',
    4: 'gem',
    5: 'currency',
    6: 'divination',
    8: 'prophecy',
    9: 'foil',
}

# Keywords in fragment items
FRAGMENTS = [
    'Sacrifice',
    'Key',
    'Mortal',
    'Fragment',
    'Emblem',
    'Writ',
    'Divine Vessel',
    'Goddess',
    'Sacred Blossom',
    'Breachstone',
    'Lure',
]

# Selectable options for ComboBox filters
COMBO_ITEMS = {
    'Category': ['Any', 'Normal', 'Magic', 'Rare', 'Unique', 'Foil', 'Any Non-Unique'],
    'Rarity': [
        'Any',
        'Bow',
        'Claw',
        'Dagger',
        'Rune Dagger',
        'One Handed Axe',
        'One Handed Mace',
        'One Handed Sword',
        'Sceptre',
        'Staff',
        'Warstaff',
        'Two Handed Axe',
        'Two Handed Mace',
        'Two Handed Sword',
        'Wand',
        'Fishing Rod',
        'Body Armour',
        'Boots',
        'Gloves',
        'Helmet',
        'Shield',
        'Quiver',
        'Amulet',
        'Ring',
        'Belt',
        'Trinket',
        'Skill Gem',
        'Support Gem',
        'Jewel',
        'Abyss Jewel',
        'Cluster Jewel',
        'Flask',
        'Map',
        'Map Fragment',
        'Maven\'s Invitation',
        'Scarab',
        'Watchstone',
        'Leaguestone',
        'Prophecy',
        'Divination Card',
        'Captured Beast',
        'Metamorph Sample',
        'Contract',
        'Blueprint',
        'Currency',
        'Unique Fragment',
        'Resonator',
        'Fossil',
        'Incubator',
        'Heist',
    ],
}
