RARITIES = {
    0: 'normal',
    1: 'magic',
    2: 'rare',
    3: 'unique',
    4: 'gem',
    5: 'currency',
    6: 'divination',
    8: 'prophecy',
    9: 'foil',
}

FILTER_RARITIES = ['Any', 'Normal', 'Magic', 'Rare', 'Unique', 'Foil', 'Any Non-Unique']

FRAGMENTS = [
    'Sacrifice',
    'Key',
    'Mortal',
    'Fragment',
    'Emblem',
    'Writ',
    'Divine Vessel',
    'Goddess',
    'Sacred Blossom',
    'Breachstone',
    'Lure',
]

CATEGORIES = [
    'Any',
    'Bow',
    'Claw',
    'Dagger',
    'Rune Dagger',
    'One Handed Axe',
    'One Handed Mace',
    'One Handed Sword',
    'Sceptre',
    'Staff',
    'Warstaff',
    'Two Handed Axe',
    'Two Handed Mace',
    'Two Handed Sword',
    'Wand',
    'Fishing Rod',
    'Body Armour',
    'Boots',
    'Gloves',
    'Helmet',
    'Shield',
    'Quiver',
    'Amulet',
    'Ring',
    'Belt',
    'Trinket',
    'Skill Gem',
    'Support Gem',
    'Jewel',
    'Abyss Jewel',
    'Cluster Jewel',
    'Flask',
    'Map',
    'Map Fragment',
    'Maven\'s Invitation',
    'Scarab',
    'Watchstone',
    'Leaguestone',
    'Prophecy',
    'Divination Card',
    'Captured Beast',
    'Metamorph Sample',
    'Contract',
    'Blueprint',
    'Currency',
    'Unique Fragment',
    'Resonator',
    'Fossil',
    'Incubator',
    'Heist',
]
